name: ci

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest','macos-latest' ]
        # - https://www.ruby-lang.org/en/downloads/branches
        ruby-version: [ '3.2','ruby-head','jruby-head' ]

    runs-on: "${{ matrix.os }}"

    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # - https://github.com/ruby/setup-ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
