name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest,macos-latest,windows-latest]
        version: [2.4.x,2.5.x,2.6.x,2.7.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Ruby ${{ matrix.version }}
      uses: ./
      with:
        ruby-version: ${{ matrix.version}}
    
    - name: Rake Test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
